/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.9.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as createGroup from "../createGroup";
import type * as getAllGroups from "../getAllGroups";
import type * as joinGroup from "../joinGroup";
import type * as storeUser from "../storeUser";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  createGroup: typeof createGroup;
  getAllGroups: typeof getAllGroups;
  joinGroup: typeof joinGroup;
  storeUser: typeof storeUser;
}>;
